version: 2.1

orbs:
  slack: circleci/slack@4.10.1
  utils: ethereum-optimism/circleci-utils@1.0.13

parameters:
  go_version:
    type: string
    default: 1.25.1 # update CI Go version here


jobs:
  build-and-deploy:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      # Fetch more history for diffing
      - run:
          name: Fetch git history
          command: |
            git fetch --depth 1000

      # Build forkdiff using Docker
      - run:
          name: Build forkdiff
          command: |
            docker run --volume $(pwd):/workspace \
              protolambda/forkdiff:0.1.1 \
              -repo=/workspace \
              -fork=/workspace/fork.yaml \
              -out=/workspace/index.html

      # Prepare pages directory
      - run:
          name: Build pages
          command: |
            mkdir -p /tmp/pages
            mv index.html /tmp/pages/index.html
            touch /tmp/pages/.nojekyll
            if [ "$CIRCLE_PROJECT_REPONAME" == "op-geth" ] && [ "$CIRCLE_PROJECT_USERNAME" == "ethereum-optimism" ]; then
              echo "op-geth.optimism.io" > /tmp/pages/CNAME
            fi
      - utils/github-pages-deploy:
          src-pages-dir: /tmp/pages

  build-geth:
    docker:
      - image: cimg/go:<<pipeline.parameters.go_version>>
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command: go run build/ci.go install
  unit-test:
    resource_class: xlarge
    docker:
      - image: cimg/go:<<pipeline.parameters.go_version>>
    steps:
      - checkout
      - run:
          command: go run build/ci.go test
  lint-geth:
    resource_class: medium
    docker:
      - image: cimg/go:<<pipeline.parameters.go_version>>
    steps:
      - checkout
      - run:
          command: go run build/ci.go lint
  tidy-geth:
    resource_class: small
    docker:
      - image: cimg/go:<<pipeline.parameters.go_version>>
    steps:
      - checkout
      - run:
          command: go mod tidy && git diff --exit-code
  check-sr-diff:
    docker:
      - image: cimg/go:<<pipeline.parameters.go_version>>
    steps:
      - checkout
      - run:
          name: install dasel
          command: go install github.com/tomwright/dasel/v2/cmd/dasel@v2.8.1
      - run:
          name: generate artifact and check diff
          command: |
            bash ./sync-superchain.sh
            git diff --exit-code

workflows:
  main:
    jobs:
      - build-geth:
          name: Build geth
      - unit-test:
          name: Run unit tests for geth
      - lint-geth:
          name: Run linter over geth
      - tidy-geth:
          name: Check geth go.mod file has been tidied
      - check-sr-diff:
          name: Check superchain registry bundle diff

  merge:
    jobs:
      - build-and-deploy:
          context: circleci-repo-op-geth
          filters:
            branches:
              only: optimism
