// Code generated by "stringer -type=BalanceChangeReason"; DO NOT EDIT.

package types

import "strconv"

const _BalanceChangeReason_name = "ValidatorRewardEmptyAccountByCode0StartNonceGasRefundBalanceMintBalanceBurnBlockRewardFeeTipUncleRewardTransactionFeeL1FeeDepositBaseFeeBurn"

var _BalanceChangeReason_index = [...]uint8{0, 15, 31, 44, 53, 64, 75, 87, 94, 105, 119, 125, 134, 146}

func (i BalanceChangeReason) String() string {
	if i >= BalanceChangeReason(len(_BalanceChangeReason_index)-1) {
		return "BalanceChangeReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BalanceChangeReason_name[_BalanceChangeReason_index[i]:_BalanceChangeReason_index[i+1]]
}