name: op-geth

on:
  push:

jobs:
  build:
    uses: ethereum-optimism/factory/.github/workflows/docker.yaml@f8f3cb4800e538003134fb5f50cc734c2c98d762
    with:
      image_name: ${{ github.workflow }}
      context: .
      dockerfile: Dockerfile
      gcp_project_id: ${{ vars.GCP_PROJECT_ID_OPLABS_TOOLS_ARTIFACTS }}
      registry: us-docker.pkg.dev/oplabs-tools-artifacts/images
      build_args: |
        VERSION=${{ github.ref_type == 'tag' && github.ref_name || '' }}
        COMMIT=${{ github.sha }}
        BUILDNUM=${{ github.run_number }}
    permissions:
      contents: read
      id-token: write
      attestations: write

